// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3dJBuMny42jvRIEjqIytT4CUcv4CskU',
    appId: '1:198757505016:web:1ae83ed6ff7fd412a6e80d',
    messagingSenderId: '198757505016',
    projectId: 'flutter-app-distribution-ae41e',
    authDomain: 'flutter-app-distribution-ae41e.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-ae41e.firebasestorage.app',
    measurementId: 'G-0JTHK83CLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEkBlfAligiQ-KfXdzI3qsropwhkAWnU',
    appId: '1:198757505016:android:f0b625af37ed2b37a6e80d',
    messagingSenderId: '198757505016',
    projectId: 'flutter-app-distribution-ae41e',
    storageBucket: 'flutter-app-distribution-ae41e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitReu4By6n1bOGIye4zKEfDb5b259jEo',
    appId: '1:198757505016:ios:71d6791df16c214da6e80d',
    messagingSenderId: '198757505016',
    projectId: 'flutter-app-distribution-ae41e',
    storageBucket: 'flutter-app-distribution-ae41e.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitReu4By6n1bOGIye4zKEfDb5b259jEo',
    appId: '1:198757505016:ios:71d6791df16c214da6e80d',
    messagingSenderId: '198757505016',
    projectId: 'flutter-app-distribution-ae41e',
    storageBucket: 'flutter-app-distribution-ae41e.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-3dJBuMny42jvRIEjqIytT4CUcv4CskU',
    appId: '1:198757505016:web:ec9de04c2be9518ba6e80d',
    messagingSenderId: '198757505016',
    projectId: 'flutter-app-distribution-ae41e',
    authDomain: 'flutter-app-distribution-ae41e.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-ae41e.firebasestorage.app',
    measurementId: 'G-Z1J0N6XQ6H',
  );
}
