
default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:198757505016:android:f0b625af37ed2b37a6e80d",
    firebase_cli_token: "1//03lyQ-9t9Ab1RCgYIARAAGAMSNwF-L9Ir_7EmWI34ntVOvnH-rZxrhw_nl7HB5TsH_Wj7gP0X3KGiFc4pjYTf7_VGppbnDmwvlF0",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "mostafafarar2030@gmail.com",
    release_notes: "First release Firebase App Distribution"
  )
  
  end
end
